# Generated by Django 4.2.4 on 2024-06-27 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_remove_product_category_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartproducts',
            name='shopping_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='grocery.shoppingcart', verbose_name='Корзина покупок'),
        ),
    ]
